name: twitter_clone
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_hooks: ^0.21.3+1
  flutter_riverpod: ^3.0.3
  hooks_riverpod: ^3.0.3
  riverpod_annotation: ^3.0.3

dev_dependencies:
  build_runner: ^2.7.1
  custom_lint: ^0.8.0
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  riverpod_generator: ^3.0.3
  riverpod_lint: ^3.0.3
  very_good_analysis: ^10.0.0

flutter:
  uses-material-design: true
